
set(PAL_TRAIT_TULABSOUND_SUPPORTED TRUE)
set(PAL_TRAIT_TULABSOUND_TEST_SUPPORTED FALSE)
set(PAL_TRAIT_TULABSOUND_EDITOR_TEST_SUPPORTED FALSE)

set(LY_COMPILE_DEFINITIONS PUBLIC USE_KISS_FFT=1 __LINUX_ASOUND__=1 HAVE_STDINT_H=1 HAVE_SETENV=1 HAVE_SINF=1)